### ISSUE TITLE
[PSPS] Skins dont always load

### ISSUE THREAD

**Issue by Kyoko-Kirigiri** [ProtocolSupport/ProtocolSupportPocketStuff#10]
yeah skulls work fine

**Comment by AlexCreeper25** [comment]
for me skins load on PC but not on PE. I mean, PE player cant see his skin, but can see the skin of all other players (both PE and PC players). From PC all works fine

**Comment by Kyoko-Kirigiri** [comment]
@7kasper  it dont crash anymore (: now only skins not always loading

**Comment by magicus** [comment]
When I tested now, I can see the PE player's skin correctly from PC, but from the PE (iPad) I only see the generic Steve skin on my PC player.

**Comment by 7kasper** [comment]
Try relogging with pc.

**Comment by magicus** [comment]
Relogging? As in logging out and in again? I've tried that, doesn't help. :(

**Comment by magicus** [comment]
I have now enabled online mode in server.properties. With that change, the PC player can see their own skin correctly in 3rd person view. However, even with the PS plugin re-enabled, the PE player still sees the default Steve skin... :(

**Comment by Kyoko-Kirigiri** [comment]
it works right now
