### ISSUE TITLE
[PSPE] Village(r)s crash the game.

### ISSUE THREAD

**Issue by 7kasper** [ProtocolSupport/ProtocolSupportPocketStuff#11]
No error is given in console.

**Comment by magicus** [comment]
I wonder if the behavior registered in https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues/37 gives a clue. Perhaps the client gets a broken pointer to the skin of the villager. It would certainly mostly result in a crash, but at some time, accessible but random memory could result in garbled graphics.

**Comment by 7kasper** [comment]
@magicus can it be that PC has more villager types than PE? 🤔

**Comment by magicus** [comment]
Sounds like an interesting theory. If a non-existent villager type appears, it can certainly confuse the client. 

Is it possible to hardcode the villagers to only be a single type (that is guaranteed to exist in PE)? That would be an easy way to at least disprove this theory. :)

**Comment by 7kasper** [comment]
Yes. If we remove the metadata remapper for villager types it will only be the default or zero type.

**Comment by 7kasper** [comment]
Yeah no crashes without the remapper.

**Comment by 7kasper** [comment]
Also can't see baby villagers 🤒

**Comment by 7kasper** [comment]
Actually all babies were done wrongly, this should also be fixed now.

**Comment by TacoGuyAT** [comment]
Record of this one...
https://youtu.be/l84a73N7Qt0
