### ISSUE TITLE
someone seems to have forgotten team packet?

### ISSUE THREAD

**Issue by daboluo666** [ProtocolSupport/ProtocolSupportPocketStuff#112]
team hack disappear?

**Comment by Shevchik** [comment]
Scoreboard teams dom't exist in pe.

**Comment by daboluo666** [comment]
@Shevchik but I remember bossbar can hack "scoreboard team".

**Comment by Shevchik** [comment]
No. You can offset bossbar to make it look like it is scoreboard.
But it is not scoreboard.
