### ISSUE TITLE
Bungeecord incompatibility

### ISSUE THREAD

**Issue by EmanuelSimard** [ProtocolSupport/ProtocolSupportPocketStuff#114]
Title says it all, is there a way to connect through Bungee?

**Comment by SiebeDW** [comment]
there is litterary ProtocolSupportBungeecord

**Comment by EmanuelSimard** [comment]
Yes but I'm looking for ProtocolSupportPockerStuff compatibility with Bungeecord, is this possible?

**Comment by Shevchik** [comment]
No, since it requires bukkit api and pspe api.
