### ISSUE TITLE
[PSPE] Block place issues.

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#12]
When a PE player builds a lot of blocks, only some of them are correctly propagated to the server and other players, PC or PE.

The PE player that puts the block sees them locally, which means that the world view of this player and all others diverge.

Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by Shevchik** [comment]
Most likely related to the fact that in pe you can place blocks and break blocks that are not in the player cursor (because player cursor isn't fixed in pe).

**Comment by 7kasper** [comment]
Isn't this the same as #13 ?

**Comment by 7kasper** [comment]
Can't reproduce this on android. Are you using any other plugins like an anticheat, that might screw with the things?

**Comment by 7kasper** [comment]
@magicus I can reproduce this but only if the block is more than 4 blocks away. If that is only the case, all of these issues fall under #14.

**Comment by magicus** [comment]
I agree that the issues might well be related, but as I see it there are at least two different ways the problems exhibit, which to me sounds like different problems.

One problem is that the PE player placing the blocks sees the block (and thinks everything is alright), but no other player sees them. That seems like the client thinks the placement was OK but the server did not register it.

The other issue is that blocks that was placed, previously or currently, disappears.

Hm. Or maybe it is the same thing, that the client shows the block, and depending on if it is getting an update from the server, it is displayed for a brief time, or an almost indefinitely long time.

I'm not using any plugins except PS. Plain Spigot, recently compiled out of the box.

I'll check if the problem seems related to distance of placing block.

**Comment by 7kasper** [comment]
I will try adding block update (monday or perhaps tonight), if the distance is too far, perhaps that'll solve all these issues.

**Comment by magicus** [comment]
As I commented in #14, it is a reasonable assumption that all these issues stems from the distance problem.

**Comment by 7kasper** [comment]
@magicus Should be fixed now.

**Comment by magicus** [comment]
Thank you @7kasper, it seems to work now. When I try to place a block too far away, it is immediately removed. 

However, a new issue immediately arrived. :-) A newly placed block, at the limit of my "placing radius", is not possible to break. Is there different "reaches" for placing and breaking blocks?

**Comment by magicus** [comment]
I notice that the code changes check for distance > 5 when placing blocks, but > 4 when "clicking" them. I suspect this might be the source of the discrepancy.

**Comment by 7kasper** [comment]
WDYM? Minecraft or PSPE..

**Comment by magicus** [comment]
The latest commits to PSPE. I glanced through them, and it just looked odd. But then again, it might be perfectly fine.

**Comment by 7kasper** [comment]
For PSPE it should behave like java. I can't test RN, but if java works this way too than it's ok, otherwise I might have screwed up somewhere.

**Comment by magicus** [comment]
This is still an issue, but less common. :(

I tried changing the limit to 3 to force more frequent checks and maybe eliminate some border issues. It might have improved things, but did not solve it fully.

**Comment by 7kasper** [comment]
Should be completely gone now.

**Comment by magicus** [comment]
Most of the problems are gone, but there's still a specific issue. But this bug is so messy so I'm going to accept it as fixed and close it, and open a new for the sole remaining problem.
