### ISSUE TITLE
[PSPE] SkinRestorer Bedrock Edition freeze

### ISSUE THREAD

**Issue by TacoGuyAT** [ProtocolSupport/ProtocolSupportPocketStuff#122]
SkinRestorer plugin freezes Bedrock Edition player on "Building Terrain" screen while "PC to BE" is enabled and "BE to PC" is disabled
Server is running in offline mode

Problematic tested MCs:
Windows 10 Edition: 1.11.4 (2242720)
Pocket Edition: 1.11.4 (2242712)

Plugins:
PS-Bedrock-dev, latest at the moment: BuildInfo(buildtime: 2019.06.19 at 00:54:41 EEST, buildhost: unknown, buildnumber: unknown)
PSPS: latest at the moment, was built today too
SkinRestorer: 
13.6.2 | Apr 15, 2019

Spigot: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by WesleyVanNeck** [comment]
Know just don't use skin restorer and don't use offline mode
