### ISSUE TITLE
[PSPE] When you land on blocks in creative mode with equipped elytra they stop working

### ISSUE THREAD

**Issue by TacoGuyAT** [ProtocolSupport/ProtocolSupportPocketStuff#123]
After you stop flying in creative mode and land on blocks you can't fly on elytra before you switch in survival mode and then back in creative mode

Problematic tested MCs:
Windows 10 Edition: 1.11.4 (2242720)

Plugins:
PS-Bedrock-dev, latest at the moment: BuildInfo(buildtime: 2019.06.19 at 00:54:41 EEST, buildhost: unknown, buildnumber: unknown)
PSPS: latest at the moment, was built today too

Spigot: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by WesleyVanNeck** [comment]
Know issue close
