### ISSUE TITLE
[PSPE] Lingering potions works incorrectly in Bedrock Edition

### ISSUE THREAD

**Issue by TacoGuyAT** [ProtocolSupport/ProtocolSupportPocketStuff#124]
Lingering potion appears only when it got exploded and then it just disappears in Bedrock Edition visually. Also it has black color like mob eggs when it's appeared
https://cdn.discordapp.com/attachments/442953890975973376/590687499995840512/unknown.png

Problematic tested MCs:
Windows 10 Edition: 1.11.4 (2242720)

Plugins:
PS-Bedrock-dev, latest at the moment: BuildInfo(buildtime: 2019.06.19 at 00:54:41 EEST, buildhost: unknown, buildnumber: unknown)
PSPS: latest at the moment, was built today too

Spigot: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by TacoGuyAT** [comment]
Also they have incorrect effects

**Comment by TacoGuyAT** [comment]
https://github.com/ProtocolSupport/ProtocolSupportPocketIssues/issues/97

**Comment by WesleyVanNeck** [comment]
@TacoGuyAT this is for psps this is not a issue tracker for psps

**Comment by WesleyVanNeck** [comment]
So close them all and https://github.com/ProtocolSupport/ProtocolSupportPocketIssues
