### ISSUE TITLE
Mob spawning eggs

### ISSUE THREAD

**Issue by TacoGuyAT** [ProtocolSupport/ProtocolSupportPocketStuff#125]
Second mob eggs tab, which opens first one, wrong textures, villager and zombie villager are not included in mob eggs tab
https://cdn.discordapp.com/attachments/442953890975973376/590691820225298432/unknown.png

Problematic tested MCs:
Windows 10 Edition: 1.11.4 (2242720)

Plugins:
PS-Bedrock-dev, latest at the moment: BuildInfo(buildtime: 2019.06.19 at 00:54:41 EEST, buildhost: unknown, buildnumber: unknown)
PSPS: latest at the moment, was built today too

Spigot: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by WesleyVanNeck** [comment]
Known also
