### ISSUE TITLE
[PSPE] Clear command doesn't clears inventory fully in Bedrock Edition

### ISSUE THREAD

**Issue by TacoGuyAT** [ProtocolSupport/ProtocolSupportPocketStuff#126]
/clear clears only hotbar

Problematic tested MCs:
Windows 10 Edition: 1.11.4 (2242720)

Plugins:
PS-Bedrock-dev, latest at the moment: BuildInfo(buildtime: 2019.06.19 at 00:54:41 EEST, buildhost: unknown, buildnumber: unknown)
PSPS: latest at the moment, was built today too

Spigot: This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by WesleyVanNeck** [comment]
This works fine for my server so are you using essentials?

**Comment by TacoGuyAT** [comment]
it was default minecraft clear, but i changed Spigot on Paper (Paper-632) and /clear works fine now in bedrock edition. forgot to say, that /clear was working fine in java edition
