### ISSUE TITLE
[PSPE] Blocks placed by PE player are sometimes immediately removed

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#13]
Sometimes when a PE player plays a block, it just flashes by briefly and is then removed. (Presumably the client shows it as being placed, but the server sends an update shortly after without the block).

Being persistent and trying to place the block again and again seems to help sometimes (but not always). Other times the player needs to change position and try again, and this can help. But sometimes it is almost impossible to place a block at all, even though it should be possible.

Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by 7kasper** [comment]
On Iphone mm? Perhaps this is due to the server updating the inventory at the same time as the block is placed.

**Comment by magicus** [comment]
On an iPad, yes. (This goes for all bugs I'm reporting)

**Comment by 7kasper** [comment]
Let's wrap this in #12
