### ISSUE TITLE
Be able to place blocks further away (as in offline PE)

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#14]
I'm not sure if this is a fundamental difference between PE and PC, but my kids are complaining that it is not possible to place block far away, only really close. So there seem to be some distance limit that differs between Spigot+PSPE and a PE server like Nukkit, or single-player on PE.

Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by 7kasper** [comment]
Correct, PE can place blocks further and the server won't accept that. We probably can't fix this, but it would be possible to hack into PSPS. (Overrule the server and let the blocks be placed further if it is PE player.

**Comment by 7kasper** [comment]
Can you check the distance for me? It should be 4-5 blocks in survival.

**Comment by magicus** [comment]
It's a bit unclear exactly how to measure this, but "4-5" blocks seems like a good description. If I'm flyting, start by placing a block right under me, and then continue placing blocks next to it, I can do at least 4 without issues. Number 5 seems ok, but at 6 I can repeatedly get to the issue where I place the first block OK, but when I place the second block on top of them, both disappears.

**Comment by magicus** [comment]
And when testing with a PE and PC player at the same time and checking, I can verify that block 5, that seemed to work OK from PE's perspective, was not shown to the PC player. So yes, it is possible that all the block issues stem from this.

**Comment by magicus** [comment]
As for a PSPE option, I think that would be a good idea. For my use case, a family creative server where the kids use iPads and I use the Java Edition, I'm perfectly OK with them being able to place blocks like they are used to.
