### ISSUE TITLE
[PSPE] When placing a new block, adjacent blocks can disappear

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#15]
When a PE player places two blocks on top of each other, sometimes both blocks just disappear.

This can be the result of the other bugs reported, like for instance that the first block was never properly registered by the server, and the second block was not really "possible" to place, and when an update later arrived, it showed the position of the first block as empty as well.

Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by 7kasper** [comment]
Let's wrap all these bugs together in #12
