### ISSUE TITLE
[PSPE] When selecting a fence in the inventory, it gets converted to dark oak

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#16]
When a PE player selects a fence, of any type of wood, it shows up in the hotbar for a split second, and is then replaced by a dark oak fence.

Similarily, if you select a mushroom block of any color (e.g. red), it gets converted into the brown/beige mushroom block.

This is on an iPad. Reproduced at mcpeinventory#de1cfdda28de4db41e4581f2e245cff6285c79e1

**Comment by 7kasper** [comment]
😉

**Comment by MrPowerGamerBR** [comment]
Probably I made some wrong remaps.

Does this happen only in creative mode, survival mode or both? Does this happen when taking a item from creative mode?

It is strange that it is replaced by a *dark oak* fence, not just a normal oak fence.

(Can you even get mushroom blocks from creative mode?)

**Comment by MrPowerGamerBR** [comment]
Can confirm, happens when taking fences from creative mode.

**Comment by MrPowerGamerBR** [comment]
whoops

**Comment by MrPowerGamerBR** [comment]
Also, it seems it is a bug when converting fences from PE to PC ONLY when taking it from creative mode, block/item remaps are unaffected

**Comment by MrPowerGamerBR** [comment]
Fixed fence issue in https://github.com/ProtocolSupport/ProtocolSupport/commit/dfc55c76fe3004967743538bf3ebce4b4150cc31

**Comment by MrPowerGamerBR** [comment]
Update: The mushroom block issue is related to the MUSHROOM BLOCK, not the mushroom block that is used in stews and etc etc etc.

(I think you can't even get that block in creative mode in Java creative but yeah)

**Comment by 7kasper** [comment]
No other blocks are affected? :thinking:

**Comment by magicus** [comment]
Confirm fix. Thank you!

I've tasked my kids with checking all other items. :)

**Comment by MrPowerGamerBR** [comment]
@magicus next time, please create a issue with all the broken blocks (and create a checklist!

- [ ] like this
- [ ] wow
- [ ] such check list
- [ ] so fun

**Comment by magicus** [comment]
Ok! It does not seem to be any more problematic blocks. They didn't find any quickly, and then they got bored... I'll let you know if I find more.
