### ISSUE TITLE
psps dont work with psbpe

### ISSUE THREAD

**Issue by Kyoko-Kirigiri** [ProtocolSupport/ProtocolSupportPocketStuff#19]
plugin load but flouting text and other tings (and leting me join)

[meeep error.txt](https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/files/1754357/meeep.error.txt)
[new.txt](https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/files/1754363/new.txt)

**Comment by Kyoko-Kirigiri** [comment]
i give you guys some log

**Comment by 7kasper** [comment]
Psps is out of date. Go back to old pspe build or wait using psps until it is updated.
