### ISSUE TITLE
[PSPE] The day cycle is out of sync between PC and PE

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#21]
The time of day is interpreted differently in PC and PE. If I do e.g. "/time set day", both clients report "Time set to 1000". But while this appears as day in PC, on PE it appears as twilight. And "/time set night", both reports time set to 13000, but while it is night on PC, it is like late afternoon on PE.

**Comment by 7kasper** [comment]
Can you check if the sun is roughly in the same position? PE has more shaders so it might just that it displays morning longer.

**Comment by magicus** [comment]
No, it's completely messed up. When it's night in PC, moon and stars are showing, the sun is up but low at the horizon on PE.

Possibly, the moon is at the same position as the sun, if that's what you're asking?

**Comment by 7kasper** [comment]
Perhaps there is some offset. Quite simple to fix, but we need to know the right value.

**Comment by magicus** [comment]
I checked https://minecraft.gamepedia.com/Day-night_cycle to get some fix points to test with. It was mostly confusing, but at least one thing was clear: at 6000, it should be the sun at zenit (and it was with PC), but with PE it was the moon at zenit!

**Comment by magicus** [comment]
I'll try to see if I can make some more sense out of this...

**Comment by magicus** [comment]
On 18000, the moon should be at zenit; in PE instead it's the sun that is at zenit.

Possibly the entire day/night cycle is inverted. I'm not sure if the cycle is perfectly symmetrical, or if there's some way to tell if sunrise is treated as sunset, or vice versa.

**Comment by 7kasper** [comment]
Checked on windows10 and my android phone, the sun seems fine. On my dads tablet the sun is not even visible but it is day when it should be and night when it should be. 🤔 🤔 🤔

**Comment by magicus** [comment]
That's really strange. I'll check this too on my W10 client when I can boot to it.

**Comment by 7kasper** [comment]
Can ypu check if this is still a thing? Thanks to @caoli5288 it might be fixed.

**Comment by magicus** [comment]
This is now fixed! Horray! :) Verified that moon is at zenith at 18000, and sun is at zenith at 6000.

It is still somewhat brighter than expected with "time set night", but that might be just the shader thing.
