### ISSUE TITLE
[PSPE] Hitting mobs does not seem to inflict correct amount of damage

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#23]
When hitting mobs, an extreme amount of damage is needed to kill them, for a PE player. For instance, killing a duck with a diamond sword takes ~3 hits. For a PC player, or a normal PE server, a single hit should just bring them down immediately.

Hitting a zombie with a diamond sword takes like 10 hits, instead of a few. My guess is there's some scaling issue about the size of 5-10 wrong.

**Comment by 7kasper** [comment]
This is due to PE not having the new combat yet. If you want fix RN get old combat mechanics on your server. This will probably solve it. PE is unlikely to receive new combat system and Mojang might be refitting the combat system again. If this stays for a while, we'll have to make sure in PSPS that the damage inflicted by PE is averaging around that of PC.

**Comment by magicus** [comment]
I installed OldCombatMechanics. It helped somewhat, but not fully. For instance, the duck now takes two strikes by the diamond sword to kill, instead of three as before. On PC, I can kill it with a single stroke both with and without OldCombatMechanics.

So unless OldCombatMechanics is not working properly, this does not really seem like the full explanation..?

**Comment by magicus** [comment]
This actually started working when I tried right now! I don't know what you changed during the week, but something fixed this. I have not verified completely that the damage is equivalent, but it "feels" right. Monster need a couple of hits, small animals die right away.

I think you can close this.

**Comment by 7kasper** [comment]
Yeah that seems ok. So to everyone, if you want equal combat for PE right now get oldcombatmechanics, untill the combat system changes again.

**Comment by magicus** [comment]
I was a bit unclear before. After whatever fixed this, the OldCombatMechanics was not necessary. I suspect it changed some finer detail of combat, but even without it, things were not wildly wrong.
