### ISSUE TITLE
[PSPE] Cannot inflict damage on skeletons by hitting them

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#24]
Trying to strike a skeleton with a sword, or any other item, does not inflict any damage at all (they do not flash red or react). Shooting on them with bow and arrow, or throwing a snowball, works.

I don't think this is related to #23, but who am I to know...

**Comment by 7kasper** [comment]
This seems really weird.

**Comment by Kyoko-Kirigiri** [comment]
same for creepers

**Comment by magicus** [comment]
You are right, creepers have the same issue.

**Comment by magicus** [comment]
I noticed another strange thing, which probably is related. If you look up towards the sky, creepers and skeletons disappear from view. If you look back down again, they reappear. There might be a discrepancy between where the client and the server believes the mob is?

**Comment by Kyoko-Kirigiri** [comment]
yeah

**Comment by magicus** [comment]
I also checked with the PC client. It looked alright. The PE player was standing right next to the mob, swashbuckling wildly straight through the creeper. So it is not an error of positioning.

**Comment by 7kasper** [comment]
Can confirm this issue although it seems I can hit the skeleton but only sometimes. Weird.

**Comment by magicus** [comment]
This got me testing some more. It seems to be some boundingbox/placement issue. If I hit the skeletons on the legs, it seems to work every time, or almost every time. If I hit them on the head, it never works.

**Comment by magicus** [comment]
Small update: this goes for ghasts as well.

**Comment by 7kasper** [comment]
Hahahaha I spelled height wrong :P
