### ISSUE TITLE
[PSPE] Frames are not showing for PE players

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#25]
Frames (the "painting-like" item that you can hang on walls) does not show for PE player. If a PE player places a frame, a PC player will see the frame appear, but not so the PE player that placed it. If a PC player places a frame, the PE player will not see it either.

**Comment by magicus** [comment]
FWIW, paintings seem to work fine.

If a block with a frame on it is smashed by the PE player, a frame item is sometimes dropped, but it disappears quickly if you try to approach it. (?) Don't know if that has anything to do with anything...

**Comment by 7kasper** [comment]
PSPS isn't updated yet, but this can be used to fake item frames. (They are blocks in PE and entities in PC so yeah, involved alot of hacking so it is a feature of PSPS)
