### ISSUE TITLE
[PSPE] Arrows do not respect vertical aiming

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#29]
When a PE player fires an arrow, it flies in the direction he/she is looking, but it always hits the floor. When flying some distance away from a wall, I get the impression that it travels in a straight horizontal line starting from the player's feet, regardless of how high/low the player is aiming.

**Comment by Kyoko-Kirigiri** [comment]
i can comfirm

**Comment by 7kasper** [comment]
Hmmmmmmmmm

**Comment by 7kasper** [comment]
I cannot confirm. For more pressing matters this will also be put on hold.

**Comment by 7kasper** [comment]
Can you give me steps to reproduce or provide a video? I find this a bit vague and cannot reproduce

**Comment by magicus** [comment]
This is now fixed in mcpeinventory.
