### ISSUE TITLE
[PSPE] [minor] Animals is responding erratically to being shown food

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#31]
When trying to get animals to follow by showing them foodstuff, this does not work properly. After a while the animal follows, but it seems to take multiple attempts. I have not been able to figure out exactly what is wrong, but it does not "feel" right. The response is usually rapid and clear.

**Comment by MrPowerGamerBR** [comment]
Would this be a PSPE issue? This seems more likely a Minecraft (Java) issue.

Could you check if the proper food is showing correctly on a PC client when a PE client tries to show foods to an mob?

**Comment by magicus** [comment]
I tested more thoroughly, with both PC and PE. I think it's probably just a difference between how the PE stand-alone game works compared to the Java server. In PE, the animals are much more responsive. It's not a PS issue.
