### ISSUE TITLE
[PSPE] Teleported to Nether (?) and back when joining server

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#33]
When I join the server from PE, I get a strange black sky, the sound of teleportation playing over and over, the screen flashes to pitch black and the strange black sky, for multiple seconds, before I finally join the server where I left it, on the Overworld.

**Comment by AlexCreeper25** [comment]
Happens to me too. It shows the end teleportation screen, then the nether one, and then I finally spawn where I was last time...

**Comment by Shevchik** [comment]
Works as intended. The double dimension switch is there to prevent possible issues related to bungeecord and instant after server join world switch issues.

**Comment by AlexCreeper25** [comment]
Ok, thanks

**Comment by magicus** [comment]
Would it be possible to disable this if one wish not to use bungeecord? I'm running a local server at home, and my kids are complaining. :-/

**Comment by Shevchik** [comment]
Even if you are not running bungeecord, you will encounter issues if you have some plugin that changes worlds on player join.

But you can remove that (at least the double dim switch, the 5 second delay after join and dim switch will stay), by removing 
https://github.com/ProtocolSupport/ProtocolSupport/blob/mcpenew/src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Login.java
lines 89 and 90.

**Comment by AlexCreeper25** [comment]
After removing those lines, compiling fails.

**Comment by 7kasper** [comment]
@AlexCreeper25 https://github.com/ProtocolSupport/ProtocolSupport/blob/dac525d0ab7d15c105c6b9d3154be94ebad7005b/src/protocolsupport/protocol/packet/middleimpl/clientbound/play/v_pe/Login.java#L109 109 & 110 for mcpeinventory.
