### ISSUE TITLE
[PSPE] Skin of own avatar is not shown in in inventory

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#35]
In PE, when you look at yourself in the inventory, you will only see the generic Steve skin, not your own custom skin.

**Comment by 7kasper** [comment]
Psps needs a bit of a rewrite.

**Comment by 7kasper** [comment]
You probably needed a relog on both players afyer a while for all the skins to show. Also the problem might have been with mineskin and maybe they fixed something.
