### ISSUE TITLE
[PSPE] Sand falling down incorrectly

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#36]
When you break a block below sand, the sand block(s) above disappears and then reappears in place one step down, instead of showing a moving motion as in normal PE play.

**Comment by 7kasper** [comment]
Yes. It isnt implemented yet. Will maybe do that today.

**Comment by magicus** [comment]
Is there som master list of known missing functionality? Then I wouldn't have to open bugs for known issues. Or is it just as good if I open bugs, to create such a tracking list?

**Comment by 7kasper** [comment]
Yes you cab open them because I forget some, but others are listed on https://github.com/ProtocolSupport/ProtocolSupport/projects/2

**Comment by 7kasper** [comment]
Fixed
