### ISSUE TITLE
[PSPE] Spawning villager in Nether give the mob broken skin

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#37]
When my son spawned a villager in Nether, it showed up with a random pattern as skin. Looked like uninitialized memory. He spawned a second, same thing. With the third villager, they all got the correct skin. (Probably then it loaded correctly.)

**Comment by magicus** [comment]
When I tried to reproduce this, my first spawned villager looked OK, but the second crashed my client. :-( Probably the same issue, some non-existent resource causing a crash in my case but not for my son by pure chance.

**Comment by 7kasper** [comment]
I think dublicate of #11..
