### ISSUE TITLE
[PSPS] Client crash when teleporting to Nether

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#38]
When a PE player tries to teleport to Nether, the client crashes. On a reconnect, however, the player is in the Nether. But in some cases, all subsequent reconnects fails (client just keeps crashing until I remove the player data).

**Comment by magicus** [comment]
And, for the record, I have not made the patch suggested in https://github.com/ProtocolSupport/ProtocolSupportPocketStuff/issues/33.

**Comment by 7kasper** [comment]
If using psps turn off the dimension switch hack as it is obsolete due to the dim switch.

**Comment by magicus** [comment]
So, the crash is related to PSPS. When I removed PSPS as a plugin, teleporting seemed to work fine. (I only tested once, though). I restored PSPS, and changed config.yml to set dimension to false. But the client crashed anyway. :( So whatever issue PSPS is causing, it's not disabled by disabling the hack in config.yml.

**Comment by magicus** [comment]
Seems to work fine now. Don't know if anything actually changed with the code or it's just me failing to reproduce it, but I'll close it.
