### ISSUE TITLE
ProtocolSupportPocketStuff does not work

### ISSUE THREAD

**Issue by Encode17** [ProtocolSupport/ProtocolSupportPocketStuff#40]
ProtocolSupportPocketStuff does not allow Minecraft Pocket Edition player to join to the Spigot 1.12.2 server with mcpenew or mcpeinventory ProtocolSupport.
Screen: https://imgur.com/a/l8FRr (translation: Connecting to the external server..)
In the Minecraft Pocket Edition player is unnable to estabile connection with the server - pocket minecraft does not connect to the server.
There is no errors, messages or logger outputs in console (I have enabled debug mode, but still nothing).
I am using any mcpe branch of ProtocolSupport.jar and ProtocolSupportPocketStuff.jar on the Spigot 1.12.2.
Is there something to do to make connection avaible via pocket edition?
Thanks for any help.

**Comment by caspervanneck** [comment]
all ready known

**Comment by Encode17** [comment]
Will it be working in near future :/?

**Comment by MrPowerGamerBR** [comment]
maybe

**Comment by 7kasper** [comment]
🔜

**Comment by 7kasper** [comment]
PSPS is in active development and we won't support stabilty yet, but most things have been updated RN and you can test it in its hacky phase.
