### ISSUE TITLE
Memory leak in teams hack

### ISSUE THREAD

**Issue by caoli5288** [ProtocolSupport/ProtocolSupportPocketStuff#42]
Some plugin send very lots fake teams packets for scoreboard. It's continuous eat memory.

![qq 20180326113339](https://user-images.githubusercontent.com/3120587/37885744-8c788a08-30e9-11e8-897d-1df96c2ca768.png)

**Comment by 7kasper** [comment]
Teams will be removed if PE gets it. Meanwhile you should disable the hack inside the options.

**Comment by 7kasper** [comment]
Teams are removed and will be implemented when they arrive in PE.
