### ISSUE TITLE
[PSPE] Furnace rendering doesn't match reality

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#44]
## No fire animation
The fire animation in a furnace is not showing in PE, so there is no way to estimate how much longer the fuel will last.

## Arrow filling too fast
The white arrow animation showing the progress of the smelting is moving too rapidly. For instance, when cooking mutton, the arrow fills in ~5 seconds, but the mutton has not actually finished cooking until 10-11 seconds. So there's a long wait after the arrow is filled before the result is finished.

My rough timing attempts show that it's about twice as fast, but it's hard to get good measurements.

Also, if the fuel runs out before the product is finished, in a normal PE game the arrow "unfills", giving you some chance to add new fuel. This animation is not showing either.

Edit merged #45 into this to fix them at the same time (remapping is done very simmilar)

**Comment by 7kasper** [comment]
This used to work, very annoying its back shitty again. It will take me some time to get back to this.
