### ISSUE TITLE
[PSPE] Furnace arrow is filling too fast

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#45]
The white arrow animation showing the progress of the smelting is moving too rapidly. For instance, when cooking mutton, the arrow fills in ~5 seconds, but the mutton has not actually finished cooking until 10-11 seconds. So there's a long wait after the arrow is filled before the result is finished.

My rough timing attempts show that it's about twice as fast, but it's hard to get good measurements.

Also, if the fuel runs out before the product is finished, in a normal PE game the arrow "unfills", giving you some chance to add new fuel. This animation is not showing either.

**Comment by 7kasper** [comment]
Merged with #44
