### ISSUE TITLE
[PSPE] Survival fly doesn't like to work

### ISSUE THREAD

**Issue by Speentie8081** [ProtocolSupport/ProtocolSupportPocketStuff#48]
There is an issue with player#setAllowFlight(boolean arg0) where if you set allow flight to true it will still not allow you to fly in survival mode. This prevents thing's like double jump in hub and in mini-games from working.

**Comment by Remu-2018** [comment]
yes comvurmt with essentials

**Comment by 7kasper** [comment]
Fixed.
