### ISSUE TITLE
[PSPE] Move wrongly when run on stairs and slabs.

### ISSUE THREAD

**Issue by MikuSnow** [ProtocolSupport/ProtocolSupportPocketStuff#64]
![image](https://user-images.githubusercontent.com/7759441/41083109-f8bfde84-6a62-11e8-8b26-31666e2b3e0f.png)

Run fast on it.
Player will tp back by server.

**Comment by Wesley-VanNeck** [comment]
@MikuSnow  already known and duplicated

**Comment by 7kasper** [comment]
Duplicate of #34.
