### ISSUE TITLE
[PSPE] Double chest in PE is wrongly rendered

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketStuff#66]
Double chests are rendered in PE as two single chests, but they work as intended (they both open on interaction and the inventory is the double chest one)

Using PaperSpigot on 1.12.2, ProtocolSupport "mcpeinventory", commit ProtocolSupport/ProtocolSupport@f989fc0060093b526aef363833c6b166d068ab0f

**Comment by 7kasper** [comment]
I think we have another issue already open for this.
