### ISSUE TITLE
[PSPE] Some blocks are not correctly mapped in PE

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketStuff#67]
A list of blocks that I found
- Shulker boxes (all colors), they will be eventually replaced by Glazed Terracotta or update! blocks on PE
- Extended pistons
- Redstone comparator (when the comparator is powered the 2-torch side doesn't turn on on PE but it is on PC)
- Stonecutter (it exists on PE but it gets replaced with Purple Glazed Terracotta on Java, creative only issue)
- Minecart with Hopper (it becomes a normal minecart once placed)
- Minecart with Furnace (it doesn't exist on PE)
- Observer (placing it will crash PE)
- Item frame (placing it will crash PE)
- Maps (all maps in Java should be locator maps in PE, all normal maps crafted in PE should be automagically converted to locator maps)
- Stained Glass Blocks, Concrete Powder, Concrete, Glazed Terracotta, Shulker Boxes (offset problem, the Light Blue Stained Glass Block turns into Chorus Fruit) @magicus 
- more research needed

**Comment by magicus** [comment]
You can add stained glass blocks (but not stained glass panes) to this list. They get the wrong color, and light blue glass blocks get turned into chorus fruit.

**Comment by magicus** [comment]
Btw, I've found the ExMaple world useful to check different blocks:

https://github.com/overviewer/Minecraft-Overviewer-Addons/tree/master/exmaple

**Comment by magicus** [comment]
I think all colored blocks are wrong, like wool, concrete powder and concrete.

**Comment by magicus** [comment]
Not all colored blocks are wrong. The following are correct:
* bed
* banners
* wool
* carpets
* terracotta
* glass panes

The following are incorrect:
* concrete powder
* concrete
* glazed terracotta
* shulker boxes
* glass blocks

The ones that gets miscolored seem to follow the same pattern, e.g. a black glass block gets blue, and black concrete gets blue. Some gets mapped to a different color, and some gets mapped to a different kind of block.

I get the impression that there is some kind of consistent offset from a certain point. I could bet that the ones that are broken all have a higher block id (or however now that thing is represented) than the ones that are working.

**Comment by magicus** [comment]
The colored blocks, at least, will be solved by PR #871.

**Comment by magicus** [comment]
PR #871 solved most colored blocks, but not colored shulker boxes. They are still messed up. So are everything purpur related too (slabs, pillars, blocks and stairs). It's really a mess. It might be a good idea actually to await the 1.13 id-to-namespace conversion for Java...

**Comment by 7kasper** [comment]
Please reopen if shulker boxes are still an issue.
