### ISSUE TITLE
[PSPE] Boats and players' view in them are wrongly placed

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketStuff#75]
You can ride them though

![Picture1](https://user-images.githubusercontent.com/13177694/42358899-4b2f03e2-80df-11e8-82c9-7063545db3c7.png)
![Picture2](https://user-images.githubusercontent.com/13177694/42358926-6538e1ae-80df-11e8-9a32-57efcfd1f67f.png)

**Comment by 7kasper** [comment]
Please reopen if this is still an issue.
