### ISSUE TITLE
[PSPE] Some entities have weird hitboxes

### ISSUE THREAD

**Issue by AryToNeX** [ProtocolSupport/ProtocolSupportPocketStuff#76]
The wither will only take damage from its tail
The ghast will only take damage from its insides, exactly a tiny spot near the "tentacles", making it almost impossible to shoot
The boat is rendered at a lower Y value than its hitbox

More investigation needed

**Comment by 7kasper** [comment]
Yes. I need to know what hitboxes to expand / contract. Its not a hard job to do, but I don't have much time to check all hitboxes. The hitboxes are relatively easy to change if you want to try. https://github.com/ProtocolSupport/ProtocolSupport/blob/mcpenew/resources/resources/pe/entitydata.json

**Comment by 7kasper** [comment]
I think this can be closed. Please reopen on the new issue tracker if the inproper bbs prevail.
