### ISSUE TITLE
[PSPE] [Regression] Furnaces does not work properly

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#85]
When you click them, you get the furnace UI, but you cannot select the food or fuel boxes to move items there. Or at least, you can't most of the time, but sometimes it works. I have not yet been able to get the smelted result out of the output box, though. :-(

**Comment by magicus** [comment]
Seems this too was an artifact of the connection freeze. Closing.

**Comment by magicus** [comment]
Duh, sorry, I misread my own bug report. The issues with moving items is still present.

**Comment by 7kasper** [comment]
I think this is related to #82

**Comment by magicus** [comment]
Once again, it was a case of PEBKAC. :-( I didn't understand the new Pocket UI for inventories.
