### ISSUE TITLE
[PSPE] [Regression] Leaving game does not always leave properly

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#87]
When a PE player leaves the game (by selecting Save and quit), PSPE sometimes does not recognize this. When the PE player tries to rejoing, this is detected and the player is kicked out with an error message. At this point, the PSPE log says:
[23:24:09 INFO]: magicusse lost connection: Disconnected
[23:24:09 INFO]: magicusse left the game

Now the player can rejoin the server. 

This happens most of the time, but strangely enough not always.

**Comment by 7kasper** [comment]
Hmm @Shevchik any ideas on this one?

**Comment by magicus** [comment]
I'm starting to realize everything breaks down after a period of time for me. :-( Seems the entire communication between server and client dies, or mostly dies. I think this is the root cause for lot of the trouble I'm seeing, possibly including this.

**Comment by magicus** [comment]
I now believe this was just another effect of the freeze. Closing it.
