### ISSUE TITLE
[Not Impl?] Skull in PE not really shown

### ISSUE THREAD

**Issue by Mayomi** [ProtocolSupport/ProtocolSupportPocketStuff#9]
- latest spigot-1.12.2
- latest ProtocolSupport(mcpeinventory branch)
- latest ProtocolSupportPocketStuff

**Comment by AlexCreeper25** [comment]
if you use the master branch (that has no skulls implemented) it's obvious that you don't see any custom skull

**Comment by MrPowerGamerBR** [comment]
I didn't finish the skull implementation yet, it requires some refactoring and improvements.

**Comment by Mayomi** [comment]
@MrPowerGamerBR thx for reply xD

**Comment by MrPowerGamerBR** [comment]
Skull tiles should work now.

You can't see the skin when you equip it (hard to do) or on your hand (impossible) but skulls placed on the world will look ok!
