### ISSUE TITLE
[PSPE] Entitys go invisble if go near them

### ISSUE THREAD

**Issue by Wesley-VanNeck** [ProtocolSupport/ProtocolSupportPocketStuff#91]
no errors or abnormal log

**Comment by 7kasper** [comment]
What how when where?

**Comment by Wesley-VanNeck** [comment]
@7kasper if walking on a normal world and walk near a mob and a slay it it dispeard but mob is still there on Java client

**Comment by Wesley-VanNeck** [comment]
Sometime it dose it when am just walking

**Comment by Wesley-VanNeck** [comment]
This is a Akarin bug

**Comment by magicus** [comment]
I'm not sure it is. I have mobs disappearing on Spigot as well, but not due to walking close to them. But we can track that in #93 which I believe has the same root cause.
