### ISSUE TITLE
[PSPE] Mobs do not move

### ISSUE THREAD

**Issue by magicus** [ProtocolSupport/ProtocolSupportPocketStuff#93]
If you use e.g. a pig spawn egg, you will get a pig, but it will be just standing still. If you try to click on the pig, it will disappear. A connected Java client will show that the pig did indeed spawn, and walked around after that.

**Comment by 7kasper** [comment]
What the h..

**Comment by magicus** [comment]
As I said in #91, sometimes there mobs disappear completely. Perhaps the client garbage collecting them..?

**Comment by magicus** [comment]
As I said in #91, sometimes there mobs disappear completely. Perhaps the client garbage collecting them..?
